plugins {
    id 'java-library'
}

group = 'dev.zarr'
version = '0.2.1-SNAPSHOT'

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

repositories {
    mavenCentral()
    maven {
        name = 'unidata-all'
        url = 'https://artifacts.unidata.ucar.edu/repository/unidata-all/'
    }
}

dependencies {
    api 'com.fasterxml.jackson.core:jackson-databind:2.20.0'
    api 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.20.0'
    api 'com.google.code.findbugs:jsr305:3.0.2'
    api 'edu.ucar:cdm-core:5.9.1'
    api 'software.amazon.awssdk:s3:2.34.6'
    api 'com.scalableminds:blosc-java:0.3-1.21.6'
    api 'com.github.luben:zstd-jni:1.5.5-7'
    api 'com.squareup.okhttp3:okhttp:4.12.0'
    api 'org.apache.commons:commons-compress:1.28.0'
    api 'info.picocli:picocli:4.7.6'

    testImplementation platform('org.junit:junit-bom:5.14.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.junit.jupiter:junit-jupiter-params'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'com.squareup.okhttp3:mockwebserver:4.12.0'
    testImplementation 'junit:junit:4.13.1'
}

tasks.named('test') {
    useJUnitPlatform()
    workingDir = projectDir
}
